const projectsBanks = [
  {
    title: "Ask-Answer App",
    stacks: ["ReactJs", "Python (Flask)", "SQL"],
    libraries: [
      "Flask-SQLAlchemy",
      "Flask",
      "Pytest",
      "Postgres",
      "Firebase",
      "Corsproxy",
      "Node-sass",
      "React-icons",
      "React-router",
      "React-redux",
    ],
    image: "./assets/projects/askanswer.png",
    githubLink: "https://github.com/Ojerinde/Ask-Answer",
    liveLink: "",
    description:
      "ASK-ANSWER is an application where student get to ask question and their tutor get to answer it. The app API is built around a RESTful concepts and it performs all CRUD operations.",
  },
  {
    title: "GitHub Profile App",
    stacks: ["ReactJs", "SCSS"],
    libraries: [
      "react-error-boundary",
      "react-helmet-async",
      "node-sass",
      "react-icons",
    ],
    image: "./assets/projects/portfolio.png",
    githubLink: "https://github.com/Ojerinde/Github_portfolio",
    liveLink: "https://github-joe.netlify.app/",
    description:
      "In this project, I fetched my Github repositories and details using Github API, I used react-router to implement nexted routes, 404 page, I also set up Error boundary, custom hooks, and SEO.",
  },
  {
    title: "Trivia App",
    stacks: ["ReactJs", "Python", "CSS"],
    libraries: ["Flask", "Flask-SQLAlchemy", "Flask-RESTful", "Flask-Cors"],
    image: "./assets/projects/trivia.png",
    githubLink: "https://github.com/Ojerinde/Udacity-Trivia-App",
    liveLink: "",
    description:
      "Trivia app is a web-based bookshelf where user can play trivia games. They can add as well have quiz. It is an app that is built around a RESTful API which performs all CRUD operations.",
  },
  {
    title: "Fyyur App",
    stacks: ["ReactJs", "Python", "CSS"],
    libraries: [
      "WTForms",
      "Flask",
      "Flask-SQLAlchemy",
      "Flask-Migrate",
      "Postgres",
    ],
    image: "./assets/projects/fyyur.png",
    githubLink: "https://github.com/Ojerinde/Udacity-Fyyur-1",
    liveLink: "",
    description:
      "Fyyur is a musical venue and artist booking site that facilitates the discovery and bookings of shows between local performing artists and venues. This site lets you list new artists and venues, discover them, and list shows with artists as a venue owner.",
  },
  {
    title: "Calculator",
    stacks: ["ReactJs", "SCSS"],
    libraries: ["node-sass", "react-icons", "react-redux", "react-router-dom"],
    image: "./assets/projects/calculator.png",
    githubLink: "https://github.com/Ojerinde/AltSchool--Assignment-4",
    liveLink: "https://minimalcalculator-joe.netlify.app/",
    description:
      "MinimalCalculator app is an app that performs some basic mathematical operationsc and user can also view their history.",
  },
  {
    title: "MySchool App",
    stacks: ["ReactJs", "SCSS"],
    libraries: [
      "react-redux",
      "react-error-boundary",
      "node-sass",
      "react-icons",
    ],
    image: "./assets/projects/myschool.png",
    githubLink: "https://github.com/Ojerinde/MySchool",
    liveLink: "https://myschool-joe.netlify.app/",
    description:
      "In this project I implemented, React-router, Nested routes, 404 page, Error boundary, and Client-side pagination. I used randomuser.me API as my backend",
  },

  {
    title: "Natour App",
    stacks: ["HTML", "CSS (SCSS)"],
    libraries: [
      "postcss-cli",
      "autoprefixer",
      "npm-run-all",
      "concat",
      "live-server",
    ],
    image: "./assets/projects/natour.png",
    githubLink: "https://github.com/Ojerinde/Advanced_CSS--Natour-Project",
    liveLink: "https://natour-jor-el.netlify.app/",
    description: "Okay, this is a project I did for my CSS course",
  },
  {
    title: "Coffee Shop App",
    stacks: ["Python", "Dockerfile", "Shell", "JavaScript"],
    libraries: [
      "Flask",
      "Flask-SQLAlchemy",
      "Auth0 authentication system",
      "Python-Jose",
      "Postman",
    ],
    image: "./assets/projects/identity.png",
    githubLink: "https://github.com/Ojerinde/Udacity-Identity_Management-3",
    liveLink: "",
    description:
      "Coffee Shop App is a digitally enabled cafe, where students can order drinks, socialize, and study hard. The application API is built around RESTful concepts and it performs all CRUD operations.",
  },
  {
    title: "Trillo App",
    stacks: ["HTML", "SCSS"],
    libraries: ["node-sass", "npm-run-all", "concat", "parcel"],
    image: "./assets/projects/trillo.png",
    githubLink: "https://github.com/Ojerinde/Trillo_app",
    liveLink: "https://trillo-app-jor-el.netlify.app/",
    description: "In this project, I horned my FlexBox skills",
  },
  {
    title: "Nexter App",
    stacks: ["HTML", "SCSS"],
    libraries: [
      "node-sass",
      "npm-run-all",
      "concat",
      "parcel",
      "autoprefixer",
      "postcss-cli",
    ],
    image: "./assets/projects/nexter.png",
    githubLink: "https://github.com/Ojerinde/Nexter_app",
    liveLink: "https://nexter-jor-el.netlify.app/",
    description: "In this project, I horned my Grid skills",
  },
  {
    title: "OmniFood App",
    stacks: ["HTML", "CSS"],
    libraries: [
      "node-sass",
      "npm-run-all",
      "concat",
      "parcel",
      "autoprefixer",
      "postcss-cli",
    ],
    image: "./assets/projects/omnifood.png",
    githubLink: "https://github.com/Ojerinde/Omnifood",
    liveLink: "https://omnifood-jor-el.netlify.app/",
    description:
      "In this project, I used HTML and CSS to build a beautiful and responsive application",
  },
  {
    title: "Forkify Food-shop App",
    stacks: ["HTML", "SCSS", "JavaScript"],
    libraries: ["core-js", "fractional", "regenerator-runtime", "parcel"],
    image: "./assets/projects/forkify.png",
    githubLink: "https://github.com/Ojerinde/Forkify_Course-Project",
    liveLink: "https://foodshop-joe.netlify.app/",
    description:
      "Okay, this is my first project. I used HTML, CSS and JavaScript",
  },
];
export default projectsBanks;
